version: 0.0
os: linux
files:
  - source: target/*.jar            # 部署包内的相对路径（非绝对路径）
    destination: /home/ec2-user/myapp  # 目标路径
  - source: /application.properties
    destination: /home/ec2-user/myapp
  - source: scripts/*
    destination: /home/ec2-user/nyapp/scripts

permissions:
  - object: /home/ec2-user/myapp
    pattern: "**/*"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ec2-user
