version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn clean package

  post_build:
    commands:
      - echo "当前目录: $(pwd)"
      - echo "检查 scripts/ 内容:"
      - ls -lR scripts/
      - chmod -R +x scripts/
      - zip -r deploy.zip appspec.yml scripts/ target/ application.properties

artifacts:
  files:
    - target/cloudRaiser-eks-*.jar
    - scripts/**/*
    - appspec.yml
    - application.properties
  discard-paths: no