version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn --version
      - mvn clean package  # 确保生成 JAR 和复制资源文件

  post_build:
    commands:
      - echo "强制更新脚本文件..."
      - sudo rm -f scripts/*.sh  # 清理旧文件


      # 1. 确认关键文件存在
      - echo "验证构建结果:"
      - ls -l target/cloudRaiser-eks-*.jar  # 检查 JAR 文件
      - ls -l src/main/resources/application.properties  # 检查配置文件

      # 2. 将配置文件复制到构建根目录（CodeDeploy 需要）
      - cp src/main/resources/application.properties ./

      # 3. 设置脚本可执行权限
      - chmod -R +x scripts/  # 递归添加执行权限
      - chmod +x scripts/*.sh

      # 4. 打印部署包内容（调试用）
      - echo "最终打包内容:"
      - ls -l appspec.yml scripts/ target/ application.properties

artifacts:
  files:
    - target/cloudRaiser-eks-*.jar
    - scripts/**/*          # 递归包含 scripts 下所有文件
    - appspec.yml
    - application.properties
  discard-paths: no         # 保留原始目录结构