version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # 确保缩进正确，与 install: 对齐
    commands:
      - mvn --version
      - mvn install
  pre_build:
    commands:
      - echo "执行预构建步骤"
      - mvn validate
  build:
    commands:
      - echo "开始构建项目"
      - mvn compile
#  post_build:
#    commands:
#      - echo "运行单元测试"
#      - mvn test
#      - chmod +x scripts/*.sh
#
  post_build:
    commands:
      - echo "Listing deployment archive contents..."
      - ls -R scripts  # 确认脚本文件存在
      - zip -r deploy.zip appspec.yml scripts target/*.jar  # 手动打包（可选）


artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - target/*.jar
  # 移除 discard-paths 或设置为 no
  discard-paths: no


#cache:
#  paths:
#    - /root/.m2/**/*  # 确保路径正确（Maven 缓存通常在 ~/.m2/repository）